name: Run Docker Compose Locally

on:
  workflow_dispatch:

jobs:
  run-docker:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Docker Compose
        shell: powershell
        run: |
          Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass -Force
          Set-Location -Path $env:GITHUB_WORKSPACE
          Write-Host "PWD: $PWD"
          Write-Host "docker-compose.yml contents:"
          Get-Content -Path docker-compose.yml
          docker compose -f docker-compose.yml down --remove-orphans
          docker compose -f docker-compose.yml up -d
